---
title: ""
output: 
  html_document:
    theme: yeti
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

### About me...

<br>

*Hi there!* 

<br>
I am an Associate Professor in the [School of Criminology and Criminal Justice](https://ccj.asu.edu/) at [Arizona State University](https://asu.edu). My research focuses on [**network criminology**](https://jacobtnyoung.github.io/Networks.html)! Specifically, how ideas from network science can be applied to problems in criminology and criminal justice.  

I teach two courses that pertain to this research focus:  

  * An [analysis of network data](https://jacobtnyoung.github.io/SAND/) course  
  
  * A [network theory](https://jacobtnyoung.github.io/NetworkCriminology/) course  

<br>

*And*, I am the Director of Curriculum for the [Institute for Social Science Research](https://issr.asu.edu).    

<br>

*But wait, there's more!* I have recently started tinkering around with data science (because it is awesome!). Specifically, I have created a site to examine the Phoenix, AZ open data portal. The site, [R2PhX](https://jacobtnyoung.github.io/R2PhX/), explores different questions using these data.    

<br>

*Finally*, I have had the opportunity to mentor some incredible students in my career. If you are interested in who they are and they work they do, check them out at my [Mentoring](https://jacobtnyoung.github.io/Mentoring.html) page.

<br>

*Thanks for stopping by!!!*