---
title: "Workshops"
output: 
  html_document:
    theme: yeti
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>

### [R Workshop](https://jacobtnyoung.github.io/RWorkshop/)

I teach a workshop that seeks to familiarize participants with the [R](http://cran.r-project.org/) environment for statistical computing. [R](http://cran.r-project.org/) is a freely available, multi-platform,  and a powerful program for analysis and graphics. It provides a programming language that can easily be extended by the user, allows the user to produce publication-quality graphics, and is ubiquitous in statistical/quantitative courses around the world. This workshop does not require knowledge of advanced statistics methods and will not cover them in any detail. We will cover the basics of organizing, managing, and manipulating data, demonstrate basic applications, introduce programming, and discuss links to other major statistical packages.

<br>

### "Crash Course" in Network Analysis

Network science is a paradigm (i.e. a model of how the world works) that takes as its domain of interest the interdependence among units. This paradigm examines patterns or regularities in relationships (i.e. structure) among interacting units and focuses on a) how such patterns influence the behavior of these units and b) how such patterns are generated. Network analysis characterizes a broad class of techniques for describing and making inferences about research questions generated within this paradigm.

This "crash course" provides an introduction to these various ideas and techniques. Slides from the most recent workshop are available [here]().