---
title: "Mentoring"
output: 
  html_document:
    theme: yeti
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

Below is a list a students that I have been fortunate to mentor. All of them do really interesting work, so feel free to reach out and connect with them!

<br>

#### [Savanna Allen](https://search.asu.edu/profile/3285704), M.S.

-   Doctoral Student, [School of Criminology and Criminal Justice](https://ccj.asu.edu/) Arizona State University

-   *Research Interests*: juvenile delinquency, risk and protective factors for antisocial behavior, psychometrics, parenting influences on youth behavior, gender differences.

<br>

#### [A Johannes "Jon" Bottema](https://www.seattleu.edu/directory/profiles/jon-bottema-phd.php), Ph.D.

-   Assistant Professor, Seattle University

-   *Bio*: A Johannes "Jon" Bottema is an Assistant Professor in the Department of Criminal Justice, Criminology, and Forensics at Seattle University. Dr. Bottema focuses on practical research that positively impacts law enforcement agencies at various levels and the communities they serve. In particular, he is interested in evidence-based policing and the utilization of intelligence within law enforcement. His work has appeared in *Police Practice and Research: An International Journal*, *Policing: A Journal of Policy and Practice*, *Policing: An International Journal*, and *the Journal of Drug Issues*.

-   *Research Interests*: evidence-based policing, intelligence-led policing, and security studies.

<br>

#### [Katharine Brown](https://legalstudies.olemiss.edu/people/katherine-brown/), Ph.D.

-   Assistant Professor, [Department of Criminal Justice and Legal Studies](https://legalstudies.olemiss.edu/) at University of Mississippi

-   *Bio*: Katharine Brown (she/her/hers) is an Assistant Professor in the Department of Criminal Justice and Legal Studies at the University of Mississippi. Katharine’s research is on policing and homelessness. More specifically, she uses mixed methodology to evaluate innovative police strategies and coordinated responses to issues of homelessness. Her research has been published in the *Journal of Experimental Criminology*, *Behavioral Sciences and the Law*, and *Policing: An International Journal*.

<br>

#### [Suzanne St. George Coble](https://ualr.edu/criminaljustice/suzanne-coble/), Ph.D.

-   Assistant Professor, School of Criminal Justice and Criminology, University of Arkansas at Little Rock

-   *Bio*: Suzanne St. George Coble, is an Assistant Professor at University of Arkansas at Little Rock. Her research focuses on sexual violence, including theories of perpetration, rape myth acceptance, consent communication, and sexual assault case processing. She is also interested in how race, gender, and sexuality intersections influence perceptions of and responses to rape.

-   *Research Interests*: Sexual violence; police, prosecutor, and jury decision-making; social structure, inequality, and disparity; race, gender, and criminal justice; feminist and queer criminologies; qualitative methods.

<br>

#### [Eoin O‘Meara Daly](https://www.ul.ie/research/mr-eoin-omeara-daly), Ph.D.

-   Research Fellow in Youth Justice, School of Law, University of Limerick, Ireland

-   *Bio*: Eoin is a member of the Research Evidence into Policy Practice and Programmes (REPPP) Project specializing in Youth Justice and Youth Crime research in Ireland. Eoin is also part of the Youth Diversion Project Research and Development Team funded by the Department of Justice in Ireland. He holds a master’s degree in criminology and PhD in Law. His PhD research focused on community youth crime intervention, collective efficacy and young people caught up in serious crime or criminal networks. Eoin was previously a youth worker, youth justice project coordinator and then manager working on the ground in marginalized communities in Ireland. He has coordinated and managed several Garda (Police) Youth Diversion Projects over a 10-year period. He has specialist expertise in the areas of professional relationships and youth crime intervention along with youth justice or youth crime program development in communities. Eoin is the author of the Bluetown report, an examination of young peoples involved in adult criminal networks in an anonymized Irish Police district. This report is part of the overarching Greentown project that aims to address the issues of young people being exploited by criminal networks in Ireland.

<br>

#### [Chantal Fahmy](https://scholar.google.com/citations?user=R7p6oW8AAAAJ&hl=en), Ph.D.

-   Associate Professor, Department of Criminology and Criminal Justice, The University of Texas at San Antonio

-   *Bio*: Chantal received her Bachelor's degree from the University of California, Irvine; her Master's degree from California State University, Long Beach; and her Ph.D. in Criminology and Criminal Justice from [Arizona State University](https://ccj.asu.edu/). Her research focuses on reentry and reintegration from prison, health criminology, institutional corrections, and the intersection of incarceration and public health. She currently serves as an Associate Editor for *Criminal Justice and Behavior*. Her recent work has been published in *Journal of Adolescent Health*, *Social Science & Medicine*, *Journal of Criminal Justice*, *Preventive Medicine*, and *Journal of Quantitative Criminology*. In 2023, Chantal won the Alumni Award for Early Career Excellence from the School of Criminology and Criminal Justice at Arizona State University

<br>

#### [Michaela R. Flippin](https://criminal-justice.ecu.edu/michaela-flippin/), Ph.D.

-   Assistant Professor, Department of Criminal Justice and Criminology, East Carolina University

-   *Research Interests*: The nexus between formal social control and criminal justice policy and practice. To date, this work has primarily focused on the application of procedural justice in policing and 911 call-taker domains, as well as police use of technology.

<br>

#### [Danielle Haverkate](https://search.asu.edu/profile/1700805), Ph.D. Candidate

-   Senior Research Associate in the Research Unit at the Arizona Department of Corrections, Rehabilitation and Reentry

-   *Research Interests*: The collateral consequences of incarceration, correctional and public policy, and prison reentry. Her research has been published in outlets such as *Journal of Offender Rehabilitation*, *Corrections: Policy, Practice, and Research*, and *Applied Cognitive Psychology*.

<br>

#### [Arynn Infante](https://www.pdx.edu/criminology-criminal-justice/profile/arynn-infante-phd), Ph.D.

-   Assistant Professor, Portland State University, Department of Criminology and Criminal Justice

-   *Bio*: Arynn got her PhD in Criminology and Criminal Justice from [Arizona State University](https://ccj.asu.edu/) in 2020. Broadly, her work seeks to unpack the salience of race and ethnicity to punishment and social control outcomes. Recently, she developed and validated a 20-item Perceived Latino Threat Scale (PLTS) and is currently exploring how perceptions of Latino threat influence punitive border control sentiment, focusing on whether this relationship is conditional on perceived undocumented immigrant status. She also has forthcoming work exploring the importance of race and ethnicity to prison social organization, establishing a new concept, the racial code, that encourages racial group obedience, loyalty, and segregation as well as the mobilization of violence in defense of one's race in prison.

<br>

#### [Logan Ledford](https://www.logansledford.com/), Ph.D.

-   [Doctoral Candidate](https://aysps.gsu.edu/phd-student/logan-ledford/), Department of Criminal Justice and Criminology, Georgia State University

-   *Bio*: Logan Ledford obtained his Bachelor’s and Master’s degrees from East Tennessee State University, Johnson City, TN. He currently attends Georgia State University’s Criminal Justice and Criminology doctoral program, with a prospective graduation year of 2024. His general research interests include policing, network analysis, and the study of criminal groups and organizations, attempting to intersect those lines of work. His recent work has been published in *Crime & Delinquency*, *Police Practice & Research*, and *Policing: A Journal of Policy and Practice*. His dissertation aims to help better understand how social dynamics between officers condition attitudinal outcomes through using network analysis to analyze officer friendship networks.

<br>

#### [Travis Meyers](https://scholar.google.com/citations?user=WgV65qcAAAAJ&hl=en&oi=ao), Ph.D.

-   Assistant Professor, Department of Criminology and Criminal Justice, The University of Texas at San Antonio

-   *Bio*: Travis Meyers is an Assistant Professor in the Department of Criminology and Criminal Justice at The University of Texas at San Antonio. He received his Ph.D. in Criminology and Criminal Justice from [Arizona State University](https://ccj.asu.edu/) in 2018. Travis's research interests include corrections and correctional policy with a specific emphasis on offender rehabilitation and programming. He has published in the *Journal of Mental Health*, *Journal of Criminal Justice*, *International Journal of Offender Therapy and Comparative Criminology*, and *Corrections: Policy, Practice and Research*. Travis co-taught and co-developed the first Inside-Out Prison Exchange Program class in the state of Arizona and is a co-founding member of the Arizona Transformation Project.

<br>

#### [Victor Mora](), Ph.D.

-   Associate Research Analyst, San Diego Association of Governments (SANDAG)

-   *Bio*: Victor Mora received his Ph.D. in Criminology and Criminal Justice from [Arizona State University](https://ccj.asu.edu/) in 2023. He is currently an Associate Research Analyst at the San Diego Association of Governments (SANDAG) and has worked on several law enforcement and juvenile diversion program evaluations funded by federal, state, and local organizations.

-   *Research Interests*: program evaluation, policing, violent crime.

<br>

#### [Stephanie Morse](https://www.anselm.edu/faculty-directory/stephanie-morse), Ph.D.

-   Assistant Professor, Criminal Justice Department, Saint Anselm College

-   *Bio*: Stephanie Morse is an Assistant Professor in the Criminal Justice Department at Saint Anselm College. She received her Ph.D. in Criminology and Criminal Justice from [Arizona State University](https://ccj.asu.edu/) in 2022. Stephanie's work is focused on prison life and prison social organization, with a particular emphasis on rehabilitation and promoting positive outcomes with correctional populations. More broadly, she is committed to engaging in research, teaching, and service that is strengths-based, inclusive, and uplifts others.

-   *Research Interests*: Prison rehabilitation, prison life, prison social organization, corrections, qualitative methods.

<br>

#### [Raven Simonds](https://www.nycja.org/people/raven-simonds), Ph.D.

-   Senior Research Analyst at the New York City Criminal Justice Agency

-   *Research Interests*: The collateral consequences of jail and prison, social support and social networks, public policy, and applied quantitative methods. Her research agenda broadly aims to demonstrate the value of supportive actions made by others and provide practical solutions for how this can be enhanced. Raven's recent work has been published in the *International Journal of Housing Policy* and the *Journal of Offender Rehabilitation*.

<br>

#### [Logan J. Somers](https://cbss.georgiasouthern.edu/justice/current-faculty-staff/logan-somers/), Ph.D.

-   Assistant Professor in the Criminal Justice and Criminology Department at Georgia Southern University

-   *Research Interests*: Emerging issues within policing which includes officer experience, use of force, police culture, and evidence-based policing.

<br>

#### [Connor Stewart](https://search.asu.edu/profile/3133265), M.S.

-   Doctoral Student in the [School of Criminology and Criminal Justice](https://ccj.asu.edu/) at Arizona State University

-   *Research Interests*: criminological methods and theory, political violence, gangs, and organized crime.

<br>

#### [D'Andre Walker](https://legalstudies.olemiss.edu/people/dandre-walker/), Ph.D.

-   Assistant Professor, [Department of Criminal Justice and Legal Studies](https://legalstudies.olemiss.edu/), University of Mississippi

-   *Research Interests*: Primary research and teaching interests include criminology, gender and crime, juvenile delinquency, juvenile justice, and race and crime.

<br>

#### [Seth Watts](https://sethbwatts.com/), Ph.D.

-   *Research Interests*: Seth Watts is a postdoctoral researcher at Arizona State University and an incoming Assistant Professor at Texas State University. His research interests broadly include policing and program evaluation, with a particular focus on the role of the police in the opioid crisis and related public health issues, and technological innovation within police departments. His work has recently been published in the *American Journal of Public Health* and the *Journal of Criminal Justice*. 

<br>

------------------------------------------------------------------------

###  {.tabset .tabset-fade .tabset-pills}

<p align="center">

[Back to home page](https://jacobtnyoung.github.io/)

</p>

<br>
