---
title: "Writing"
output: 
  html_document:
    theme: yeti
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

----

<br><br>

### [Curriculum Vitae](https://github.com/jacobtnyoung/jacobtnyoung.github.io/raw/master/CV_YOUNG_distribute.pdf)   
<br>

### Peer-Reviewed Articles, Book Chapters, & Other Publications 

Here is my body of research. The DOIs are hyperlinked to the title.

----

<br>

**Young, Jacob T.N.**, Travis J. Meyers, Stephanie J. Morse. 2023. What is ‘prison culture’?: [Developing a Theoretical and Methodological Foundation for Understanding Cultural Schema in Prison](https://onlinelibrary.wiley.com/doi/10.1111/1745-9125.12335). *Criminology*, 61(3), 451-448.
<br>

Simonds, Raven, Natasha Khade, and **Jacob T.N. Young**. In Press. [Does Paid Transitional Housing Impact Reentry Outcomes During COVID-19 Stay-at-Home Orders? Evidence from a Natural Experiment Within an RCT](https://www.tandfonline.com/doi/full/10.1080/19491247.2022.2097852). *The International Journal of Housing Policy*.  
<br>

Tomlinson, Tiffaney A., Daniel P. Mears, Brian J. Stults, Ryan C. Meldrum, Jillian J. Turanovic and **Jacob T.N. Young**. 2023. [The Legacy of Troubled Childhoods: Adverse Childhood Experiences, Sleep, and Delinquency](https://journals.sagepub.com/doi/10.1177/00111287221083961). *Crime & Delinquency*, , 69(10), 1919-1946.  
<br>

**Young, Jacob T.N.** and Dana L. Haynie. 2022. [Trusting the Untrustworthy: The Social Organization of Trust among Incarcerated Women](https://www.tandfonline.com/doi/full/10.1080/07418825.2020.1807588). *Justice Quarterly*, 39 (3), 553-584.
<br>

Meldrum, Ryan C., Justin W. Patchin, **Jacob T.N. Young**, and Sameer Hinduja. 2022. [Bullying Victimization, Negative Emotions, and Digital Self-Harm: Testing a Theoretical Model of Indirect Effects](https://www.tandfonline.com/doi/full/10.1080/01639625.2020.1833380). *Deviant Behavior*, 43 (3), 303-321.   
<br>

Kreager, Derek A., **Jacob T.N. Young**, Dana L. Haynie, David R. Schaefer, Martin Bouchard, and Kimberly M. Davidson. 2021. [In the Eye of the Beholder: Meaning and Structure of Informal Status in Women’s and Men’s Prisons](https://onlinelibrary.wiley.com/doi/10.1111/1745-9125.12260). *Criminology*. 59 (1), 42-72.  
<br>

Ready, Justin T. and **Jacob T.N. Young**. 2020. [The Unfulfilled Potential of Police Body Cameras in the Era of Black Lives Matter](https://slate.com/technology/2020/10/black-lives-matter-police-body-cameras.html). *Slate*.  
<br>

Davidson, Kimberly M. and **Jacob T.N. Young**. 2019. [Treatment Engagement in a Prison-Based Therapeutic Community: A Mixed-Methods Approach](https://doi.org/10.1016/j.jsat.2019.05.011). *Journal of Substance Abuse Treatment*, 103 (August): 33-42.  
<br>

Meldrum, Ryan C., **Jacob T.N. Young**, Nicholas Kavish, and Brian B. Boutwell. 2019. [Could Peers Influence Intelligence During Adolescence? An Exploratory Study](http://doi.org/10.1016/j.intell.2018.11.009). *Intelligence*, 72: 28-34.  
<br>

**Young, Jacob T.N.**, Scott H. Decker, and Gary Sweeten. 2018. [The Boston Special Youth Project Affiliation Dataset](https://www.exeley.com/journal/connections). *Connections*, 37(1&2): 85-88.  
<br>

Shjarback, John A. and **Jacob T.N. Young**. 2018. [The ‘Tough on Crime’ Arms Race: A Network Approach to Understanding the Social Mechanisms Leading to the Rise of Federal Crime Control Legislation in the United States from 1973-2004](https://link.springer.com/article/10.1007%2Fs12103-017-9395-5). *American Journal of Criminal Justice*, 43(2): 197-221.  
<br>

Kreager, Derek A., Martin Bouchard, George De Leon, David R. Schaefer, Michaela Soyer, **Jacob T.N. Young**, and Gary Zajac. 2018. [A Life Course and Networks Approach to Prison Therapeutic Communities](https://link.springer.com/chapter/10.1007/978-3-319-71544-5_20). Social Networks and the Life Course, Eds. Duane F. Alwin, Diane H. Felmlee, and Derek A. Kreager. Pg. 433-451. New York: Springer.  
<br>

**Young, Jacob T.N.** and Justin T. Ready. 2018. [A Longitudinal Analysis of the Relationship between Administrative Policy, Technological Preferences, and Body-Worn Camera Activation Among Police Officers](https://academic.oup.com/policing/article/12/1/27/2897229). *Policing: A Journal of Policy and Practice*, 12(1): 27-42.  
<br>

Boutwell, Brian A., **Jacob T.N. Young**, and Ryan C. Meldrum. 2018. [On the Positive Relationship between Breastfeeding and Intelligence](http://dx.doi.org/10.1037/dev0000537). *Developmental Psychology*, 54(8):1426-1433.  

Meyers, Travis J. and Kevin A. Wright, **Jacob T.N. Young**, and Melinda Tasca. 2017. [Social Support from Outside the Walls: Examining the Role of Relationship Dynamics with Prison Visitors](http://www.sciencedirect.com/science/article/pii/S0047235217302222). *Journal of Criminal Justice*, 52: 57-67.  
<br>

Schaefer, David R., Martin Bouchard, **Jacob T.N. Young**, and Derek A. Kreager. 2017. [Friends in Locked Places: An Investigation of Prison Inmate Network Structure](http://dx.doi.org/10.1016/j.socnet.2016.12.006). *Social Networks*, 51: 88-103.  
<br>

Kreager, Derek A., **Jacob T.N. Young**, Dana L. Haynie, Martin Bouchard, and Gary Zajac. 2017. [Where ‘Old Heads’ Prevail: Inmate Hierarchy in a Men’s Prison Unit](http://journals.sagepub.com/doi/pdf/10.1177/0003122417710462). *American Sociological Review*, 82(4): 685-718.  
<br>

Fahmy, Chantal and **Jacob T.N. Young**. 2017. [Gender Inequality in Knowledge Production in Criminology and Criminal Justice](http://www.tandfonline.com/doi/full/10.1080/10511253.2016.1233346). *Journal of Criminal Justice Education*, 28(2): 285-305.  
<br>

Meldrum, Ryan C., Melissa A. Petkovsek, Brian B. Boutwell, and **Jacob T.N. Young**. 2017. [Reassessing the Relationship between General Intelligence and Self-Control in Childhood](http://www.sciencedirect.com/science/article/pii/S016028961630126X). *Intelligence*, 60(1):1-9.  
<br>

Turanovic, Jillian J. and **Jacob T.N. Young**. 2016. [Violent Offending and Victimization in Adolescence: Social Network Mechanisms and Homophily](http://onlinelibrary.wiley.com/doi/10.1111/1745-9125.12112/full). *Criminology*, 54(3): 487-519.  
<br>

Hoeben, Evelien M., Ryan C. Meldrum, D’Andre Walker, and **Jacob T.N. Young**. 2016. [The Role of Peer Delinquency and Unstructured Socializing in Explaining Delinquency and Substance Use: A State-of-the-Art Review](http://www.sciencedirect.com/science/article/pii/S004723521630068X?np=y). *Journal of Criminal Justice*, 47: 108-122.  
<br>

Kreager, Derek A., David R. Schaefer, Martin Bouchard, Dana L. Haynie, Sara Wakefield, **Jacob T.N. Young**, and Gary Zajac. 2016. [Toward a Criminology of Inmate Networks](http://www.tandfonline.com/doi/pdf/10.1080/07418825.2015.1016090). *Justice Quarterly*, 33(6): 1000-1028.  
<br>

Flexon, Jamie L., Ryan C. Meldrum, **Jacob T.N. Young**, and Peter Lehmann. 2016. [Low Self-Control and the Dark Triad: Disentangling the Predictive Power of Personality Traits on Young Adult Substance Use, Offending, and Victimization](http://www.sciencedirect.com/science/article/pii/S0047235216300447). *Journal of Criminal Justice*, 46: 159-169.  
<br>

Ready, Justin, and **Jacob T.N. Young**. 2015. [The Impact of On-Officer Video Cameras on Police-Citizen Contacts: Findings from a Controlled Field Experiment](https://link.springer.com/article/10.1007/s11292-015-9237-8?shared-article-renderer). *Journal of Experimental Criminology*, 11: 445-458.  
<br>

Chantal, Fahmy and **Jacob T.N. Young**. 2015. [Invisible Colleagues: The Informal Organization of Knowledge Production in Criminology and Criminal Justice](http://www.tandfonline.com/doi/full/10.1080/10511253.2015.1051999). *Journal of Criminal Justice Education*, 26(4): 423-445.  
<br>

Meldrum, Ryan C., **Jacob T.N. Young**, and Peter Lehmann. 2015. [Parental Low Self-Control, Parental Socialization, Young Adult Low Self-Control, and Offending: A Retrospective Study](http://cjb.sagepub.com/content/early/2015/07/17/0093854815595662.full.pdf). *Criminal Justice and Behavior*, 42(11): 1183-1199.  
<br> 

Corcoran, Katie, David Pettinicchio, and **Jacob T.N. Young**. 2015. [Perceptions of Societal Injustice and Efficacy: Participation in Low/High Cost Forms of Collection Action](http://onlinelibrary.wiley.com/doi/10.1111/soin.12082/pdf). *Sociological Inquiry*, 85(3): 429-461.  
<br>

**Young, Jacob T.N.** and Justin Ready. 2015. [Diffusion of Policing Technology: The Role of Networks in Influencing the Endorsement and Use of On-Officer Cameras](http://ccj.sagepub.com/content/31/3/243.full.pdf+html). *Journal of Contemporary Criminal Justice*, 31(3): 243-261.  
<br>

**Young, Jacob T.N.**, Cesar J. Rebellon, J.C. Barnes, and Frank M. Weerman. 2015. [What do Alternative Measures of Peer Behavior Tell Us? Examining the Discriminant Validity of Multiple Methods of Measuring Peer Deviance and the Implications for Etiological Models](http://www.tandfonline.com/doi/pdf/10.1080/07418825.2013.788730). *Justice Quarterly*, 32(4): 626-652.   
<br>

Rees, Carter and **Jacob T.N. Young**. 2015. [Parents, Peers, and Socialization to Institutions in Childhood and Adolescence: Implications for Delinquent Behavior](https://us.sagepub.com/en-us/nam/the-nurture-versus-biosocial-debate-in-criminology/book238854). The Nurture versus Biosocial Debate in Criminology, Ed. Kevin Beaver, Pg. 283-300. Thousand Oaks.  
<br>

Ready, Justin T. and **Jacob T.N. Young**. 2014. [A Tale of Two Cities: Whether body cams succeed in increasing police transparency depends entirely on training and policies](http://www.slate.com/articles/technology/future_tense/2014/12/police_body_cams_won_t_help_unless_they_come_with_the_right_policies.html). *Slate*.  
<br>

Ready, Justin T. and **Jacob T.N. Young**. 2014. [Three Myths about Police Body Cams: Filming interactions between law enforcement and citizens might not stop the next Ferguson from happening](http://www.slate.com/articles/technology/future_tense/2014/09/ferguson_body_cams_myths_about_police_body_worn_recorders.html). *Slate*.  
<br>

**Young, Jacob T.N.**, Cesar Rebellon, J.C. Barnes, and Frank M. Weerman. 2014. [Unpacking the Black Box of Peer Similarity in Deviance: Understanding the Mechanisms Linking Personal Behavior, Peer Behavior, and Perceptions](http://onlinelibrary.wiley.com/doi/10.1111/1745-9125.12029/pdf). *Criminology*, 52(1): 60-86.  
<br>

Barnes, J.C., Kevin M. Beaver, **Jacob T.N. Young** and Michael TenEyck. 2014. [A Behavior Genetic Analysis of the Tendency for Youth to Associate According to GPA](http://www.sciencedirect.com/science/article/pii/S0378873314000021). *Social Networks*, 38: 41-49.  
<br>

**Young, Jacob T.N.** 2014. [A Sensitivity Analysis of Egocentric Measures of Peer Delinquency to Latent Homophily: A Research Note](http://link.springer.com/article/10.1007/s10940-013-9207-0). *Journal of Quantitative Criminology*, 30(3): 373-387.  
<br>

**Young, Jacob T. N.** 2014. [Role Magnets’?: An Empirical Investigation of Popularity Trajectories for Life-Course Persistent Individuals During Adolescence](http://link.springer.com/article/10.1007/s10964-013-9946-0). *Journal of Youth and Adolescence*, 43(1):104-115.  
<br>

Boman, IV, John H., **Jacob T.N. Young**, Julie M. Baldwin, and Ryan C. Meldrum. 2014. [Specifying the Sources of Misperceptions of Peer Deviance: A Tale of Two Levels](http://cjb.sagepub.com/content/41/1/91). *Criminal Justice and Behavior*, 41(1): 91-113.  
<br>

**Young, Jacob T.N.** and Frank M. Weerman. 2013. [Delinquency as a Consequence of Misperception: Overestimation of Friends’ Delinquent Behavior and Mechanisms of Social Influence](http://www.jstor.org/stable/10.1525/sp.2013.60.3.334). *Social Problems*, 60(3):334-356.  
<br>

Meldrum, Ryan C., **Jacob T.N. Young**, Callie Burt, and Alex R. Piquero. 2013. [Maternal Versus Adolescent Reports of Self-Control: Implications for Testing the General Theory of Crime](http://www.sciencedirect.com/science/article/pii/S0047235212001365). *Journal of Criminal Justice*, 41(1): 24-32.  
<br>

**Young, Jacob T.N.** and Carter Rees. 2013. [Social Networks and Delinquency in Adolescence: Implications for Life-Course Criminology](http://link.springer.com/chapter/10.1007/978-1-4614-5113-6_10). Handbook of Life-Course Criminology, Ed. Chris Gibson and Marvin Krohn, pg. 159-180. Springer.  
<br>

Meldrum, Ryan C., **Jacob T.N. Young**, and Frank M. Weerman. 2012. [Changes in Self-Control During Adolescence: Investigating the Influence of the Adolescent Peer Network](http://www.sciencedirect.com/science/article/pii/S0047235212001006). *Journal of Criminal Justice*, 40(6): 452-462.  
<br>

Meldrum, Ryan C., **Jacob T.N. Young**, Carter Hay, and Jamie L. Flexon. 2012. [Does Self-Control Influence Maternal Attachment? A Reciprocal Effects Analysis from Childhood through Middle Adolescence](http://www.springerlink.com.ezproxy1.lib.asu.edu/content/w15q76583753q30t/). *Journal of Quantitative Criminology*, 38(4): 673-699.  
<br>

**Young, Jacob T.N.**, J.C. Barnes, Ryan C. Meldrum, and Frank M. Weerman. 2011. [Assessing and Explaining Misperceptions of Peer Delinquency](http://onlinelibrary.wiley.com/doi/10.1111/j.1745-9125.2011.00232.x/abstract). *Criminology*, 49(2): 599-630.  
<br>

Corcoran, Katie, David Pettinicchio, and **Jacob T.N. Young**. 2011. [The Context of Control: A Cross-National Investigation of the Link between Social Structure, Fatalism, and Collective Action](http://onlinelibrary.wiley.com/doi/10.1111/j.2044-8309.2011.02076.x/abstract). *British Journal of Social Psychology*, 50 (4): 575-605. Special Issue: “Innovation in Theory and Research on Collective Action and Social Change”.  
<br>

**Young, Jacob T. N.** 2011. [How Do They ‘End Up Together’? A Social Network Analysis of Self-Control, Homophily, and Adolescent Relationships](https://link.springer.com/article/10.1007/s10940-010-9105-7/). *Journal of Quantitative Criminology*, 27(3):251-273.  
<br>

Meldrum, Ryan C., **Jacob T.N. Young**, and Frank M. Weerman. 2009. [Reconsidering the Effect of Self-Control and Delinquent Peers: Implications of Measurement for Theoretical Significance](http://jrc.sagepub.com/content/46/3/353.abstract). *Journal of Research in Crime and Delinquency*, 46(3): 353-376.   
<br>

----


<p align="center">
[Back to home page](https://jacobtnyoung.github.io/)
</p>

<br>